name: Build UI Beta
description: Build UI
runs:
  using: composite
  steps:
    - name: Setup Node 20.18
      uses: actions/setup-node@v4
      with:
        node-version: 20.18.0

    - name: Node not setting up properly
      shell: bash
      run: which node

    - name: failure
      shell: bash
      run: exit 1

    # - name: Setup server
    #   shell: bash
    #   working-directory: server
    #   run: |
    #     npm install
    #     npm run start-beta

    # - name: Health check
    #   id: server-health-check
    #   shell: bash
    #   working-directory: server
    #   run: curl localhost:8080
  
    # - name: Log server errors
    #   if: ${{ failure() && steps.server-health-check.conclusion == 'failure' }}
    #   shell: bash
    #   working-directory: server
    #   run: |
    #     npm run env -- pm2 logs

    # - name: Build UI
    #   shell: bash
    #   working-directory: ui
    #   run: |
    #     npm install
    #     npm run build-beta

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: build-artifact
    #     path: .\
