name: Reproduce

on:
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/node-action
